### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by MasakiMimura** [MasakiMimura/chat-space#7]
# IPアドレス
3.130.104.253

**Comment by chiii220** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by MasakiMimura** [comment]
テストしていただき、ありがとうございました。
個人アプリ開発にとりかかります。
